### ISSUE TITLE
这是啥高端程序？😳

### ISSUE THREAD

**Issue by mokizzz** [pyjnqd/Virtual_Computer_in_Java#2]
自写虚拟机 in java 吗

**Comment by pyjnqd** [comment]
一年级C++课程的一个实验

**Comment by pyjnqd** [comment]
把冯诺依曼抽象的最简单的那种，这个是他们老师练习OO编程出的实验题

**Comment by mokizzz** [comment]
Seems extremely hard

**Comment by pyjnqd** [comment]
Yes, it seems somewhat hard for a freshman.
